#!/bin/bash
source "$ROOT_PATH/recipes/essentials"
source "$LIB_PATH/system.sh"
source "$LIB_PATH/ruby.sh"
source "$LIB_PATH/security.sh"
source "$LIB_PATH/user.sh"

function install_security {
  upgrade_system
  load_essentials_conf
  set_basic_security
  create_deploy_user $USER_NAME $USER_PASSWORD "$USER_SSH_KEY"
}
